export const TRUCK_STATUS = {
    IN_SERVICE: 'IN_SERVICE',
    ON_LOAD: 'ON_LOAD',
};

export const TRUCK_TYPE = {
    SPRINTER: 'SPRINTER',
    SMALL_STRAIGHT: 'SMALL_STRAIGHT',
    LARGE_STRAIGHT: 'LARGE_STRAIGHT',
};

export const LOAD_STATUS = {
    NEW: 'NEW',
    POSTED: 'POSTED',
    ASSIGNED: 'ASSIGNED',
    SHIPPED: 'SHIPPED',
};

export const LOAD_STATE = {
    ON_ROUTE_TO_PICK_UP: 'ON_ROUTE_TO_PICK_UP',
    ARRIVED_TO_PICK_UP: 'ARRIVED_TO_PICK_UP',
    ON_ROUTE_TO_DELIVERY: 'ON_ROUTE_TO_DELIVERY',
    ARRIVED_TO_DELIVERY: 'ARRIVED_TO_DELIVERY',
    PENDING: 'PENDING',
};

export const USER_ROLE = {
    SHIPPER: 'shipper',
    DRIVER: 'driver',
};

